version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'adriffaud'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - 'adriffaud'
